Add support for auxilary mouse buttons
idolize/xcloud-keyboard-mouse pull request #69
Opened 2022-09-27 19:45 UTC by bo-carey

Add support and typing for additional mouse buttons including `MiddleClick`, `Aux4Click`, and `Aux5Click`. 

resolves #16

2022-09-27 19:48 UTC, bo-carey commented on src/shared/types.ts
> +}
I like using an enum here but I'm not opposed to changing it or removing it. Looking forward to your feedback.

2022-09-28 02:51 UTC, idolize requested changes

2022-09-28 02:51 UTC, idolize commented on src/browser/browserEventProcessor.ts
> +      if (buttonCode && codeMapping[buttonCode]) {
I believe this truthy check (`if buttonCode`) will fail if `buttonCode` is `0`.

I would update this to the following:

```ts
if (buttonCode !== undefined && codeMapping[buttonCode]) {
```

2022-09-28 02:51 UTC, idolize commented on src/shared/types.ts
> +}
Yep, enum is great, but to make it more explicit please add assigned numbers, since the numerical values are actually significant.

```ts
export enum MouseButtons {
  Click = 0,
  MiddleClick = 1,
  RightClick = 2,
  Aux4Click = 3,
  Aux5Click = 4,
}
```

2022-09-28 12:04 UTC, bo-carey commented on src/shared/types.ts
> +}
Fixed in [f867427](https://github.com/idolize/xcloud-keyboard-mouse/pull/69/commits/f867427030888c0e25f1d7a8adddca03970e048a)

2022-09-28 16:48 UTC, idolize approved these changes
LGTM I will pull and test briefly before merge 👍

2022-09-28 18:34 UTC, merged

2022-09-28 18:35 UTC, idolize commented
Works great - thanks!